[book]
title = "Marchyo Documentation"
authors = ["Marchyo Contributors"]
description = "Comprehensive documentation for the Marchyo NixOS configuration flake"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/Jylhis/marchyo"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Jylhis/marchyo/edit/main/docs/src/{path}"
additional-css = ["theme/css/custom.css"]

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true

[output.html.fold]
enable = true
level = 0

[preprocessor.links]

[build]
build-dir = "build"
create-missing = true
